### ISSUE TITLE
[BUG] Create default folder for default csv filename is not exists

### ISSUE THREAD

**Issue by LaurentOngaro** [LaurentOngaro/UEVaultManager#15]
### To reproduce

Run 'UEVaultManager edit' with a fresh install
    - an empty file should be created

the following error occurs
`
[Cli] WARNING: The file to read data from has not been precised by the --input command option. The default file name will be used.
Traceback (most recent call last):
  File "/home/laurent/.local/bin/UEVaultManager", line 8, in <module>
    sys.exit(main())
  File "/home/laurent/.local/lib/python3.10/site-packages/UEVaultManager/cli.py", line 1417, in main
    cli.edit_assets(args)
  File "/home/laurent/.local/lib/python3.10/site-packages/UEVaultManager/cli.py", line 1131, in edit_assets
    gui_fn.create_empty_file(input_filename)
  File "/home/laurent/.local/lib/python3.10/site-packages/UEVaultManager/tkgui/modules/functions_no_deps.py", line 119, in create_empty_file
    open(file_path, 'a').close()
FileNotFoundError: [Errno 2] No such file or directory: '../../../results/list.csv'
`

### Cause

the folder `../../../results` does not exists

### TODO

check and create the folder

**Comment by LaurentOngaro** [comment]
fixed in 1.6.3
