### ISSUE TITLE
[BUG] command get_token fails

### ISSUE THREAD

**Issue by LaurentOngaro** [LaurentOngaro/UEVaultManager#25]
### Description 

An error occurs when running the command 
 
### To Reproduce

1. run `UEVaultManager get-token`

### Expected behavior

A token should be displayed

## Additional informations (Optional)

following error is displayed
```
Traceback (most recent call last):
  File "D:\Projets_Perso\03d_CodePython\UEVaultManager\UEVaultManager\cli.py", line 1529, in <module>
    main()
  File "D:\Projets_Perso\03d_CodePython\UEVaultManager\UEVaultManager\cli.py", line 1488, in main
    cli.get_token(args)
  File "D:\Projets_Perso\03d_CodePython\UEVaultManager\UEVaultManager\cli.py", line 1148, in get_token
    token = self.core.egs.get_asset_token()
AttributeError: 'EPCAPI' object has no attribute 'get_asset_token'. Did you mean: 'get_item_token'?
```

**Comment by LaurentOngaro** [comment]
fixed in commit [df6773d](https://github.com/LaurentOngaro/UEVaultManager/commit/df6773d8671233a8abf5eeb6cb40bf0e65653d73)
published on next branch merge
